### ISSUE TITLE
Enable GWP-ASan to see additional debugging data in Crashlytics

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-installer-android#125]
The list of issues in the [Crashlytics dashboard for Endless Key](https://console.firebase.google.com/project/endless-key/crashlytics/app/android:org.endlessos.Key/issues) has a banner reading:

> ★ Your app has NDK crashes that can lead to security vulnerabilities. Enable GWP-ASan to see additional debugging data in Crashlytics [Learn more ↗](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android&hl=en&authuser=0#gwp-asan)

Given how useless the C backtraces are (c.f. #124) I wonder if this might be worth doing. It is [allegedly](https://developer.android.com/ndk/guides/gwp-asan?authuser=0#opt-in) just a matter of changing the `AndroidManifest.xml`:

```xml
<application android:gwpAsanMode="always">
  ...
</application>
```

**Comment by pwithnall** [comment]
I believe the manifest is generated by p4a, and hence this probably means a change in [`.p4a`](https://github.com/endlessm/kolibri-installer-android/blob/develop/.p4a).

Some simple googling of `p4a "gwpAsanMode"` doesn’t reveal the magic argument to put in there though.

**Comment by pwithnall** [comment]
Unfortunately I can’t see anything obvious in the [p4a documentation](https://python-for-android.readthedocs.io/en/latest/buildoptions/#webview) about an argument which would add an attribute to `<application>`. The closest I can see is `--meta-data`, which adds a `<meta-data>` tag beneath `<application>`.

**Comment by pwithnall** [comment]
I think [this](https://github.com/kivy/python-for-android/blob/e76826678b440ecd7fcfa31de88d4171bb70331f/pythonforandroid/bootstraps/webview/build/templates/AndroidManifest.tmpl.xml#L44-L53) is the template which p4a uses to generate `AndroidManifest.xml`. It doesn’t have the capability to add arbitrary attributes to `<application>`.

So either:
 1. We need to find another way to enable `gwpAsanMode`
 2. We need to use a custom template (if that’s possible)
 3. `p4a` needs modifying to support `gwpAsanMode` as an option

**Comment by manuq** [comment]
For reference we are using our own fork of python-for-android at tag "v2022.09.04-endless9": https://github.com/endlessm/kolibri-installer-android/blob/899a5dbef2c1b1dfeb7f4dd0bc7392d7bfb6d01c/requirements.txt#L3

The p4a repo has multiple templates for the Android manifest. We are using the webview one. Here is an example in which we managed to tweak the template: https://github.com/endlessm/python-for-android/commit/e275da0a9a4ed798eba86cdc20ea60840b7fb099

**Comment by pwithnall** [comment]
Do we not upstream things to python-for-android?

**Comment by manuq** [comment]
We managed to upstream some (specially @dbnicholson), we failed to upstream some more. And to make things worse, we started our fork from Learning Equality's own fork of p4a. @dbnicholson is the one in the Platform team that may know the details.

**Comment by dbnicholson** [comment]
> Do we not upstream things to python-for-android?

I've definitely tried (and [succeeded in most cases](https://github.com/kivy/python-for-android/pulls?q=is%3Apr+author%3Adbnicholson+)). The whole crashlytics thing should be upstreamed, but it is fairly complex in this case since it requires several pieces to work. For example, https://github.com/endlessm/python-for-android/pull/11 is a prerequisite for crashlytics and I wrote it as if I would send it upstream but never did.

**Comment by wjt** [comment]
@dbnicholson mentioned when we spoke about this that he believes that most of the crashes we're seeing are spurious and (IIUC) are caused by python-for-android unceremoniously terminating the process when it is time to quit.

**Comment by dbnicholson** [comment]
Turns out p4a __does__ have support for this in the `--extra-manifest-application-arguments` option. Except that it's basically undocumented and only in the sdl2 bootstrap. Thanks again, pythonforandroid. Should be easy to add it to the other bootstrap manifest templates and send upstream.

**Comment by dbnicholson** [comment]
Once we're using https://github.com/endlessm/python-for-android/pull/18, it should be as simple as adding the following to `.p4a`:

```
--extra-manifest-application-arguments 'android:gwpAsanMode="always"'
```
