### ISSUE TITLE
Improve local debugging of Android app

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-installer-android#138]
Basically move the local patches I have for the Makefile:
- building with a custom kolibri-explore-plugin wheel file instead of fetching latest from PyPi
- building with a custom apps-bundle.zip file instead of fetching it from Github

I have one more patch for building with custom endless-key-collections but that will change soon to be fetched at runtime.

**Comment by erikos** [comment]
Dev QA is enough here, closing.
