### ISSUE TITLE
Update to Kolibri v0.16.0-alpha15

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-installer-android#146]
Adds the ability to include thumbnails for content items with the metadata.

**Comment by erikos** [comment]
https://github.com/learningequality/kolibri/releases/tag/v0.16.0-alpha15

**Comment by wjt** [comment]
You can take inspiration from bcb05bef2c58b80fadaa76de1cf9b1d09bd5efdc

**Comment by erikos** [comment]
Great the change looks good.

**Comment by erikos** [comment]
Deployed with Ladybird 6.9-340

**Comment by erikos** [comment]
Works fine here running for some time Ladybird 6.9-340
