### ISSUE TITLE
ChromeOS: Bump Kolibri to 0.16-alpha18

### ISSUE THREAD

**Issue by manuq** [endlessm/kolibri-installer-android#156]
It has been released: https://github.com/learningequality/kolibri/releases/tag/v0.16.0-alpha18

**Comment by pwithnall** [comment]
Stealing this :runner: :dash:

**Comment by pwithnall** [comment]
https://github.com/endlessm/kolibri-explore-plugin/pull/693 is needed to fix the app on Android WebView <80, which is what my ChromeOS machine is using (as it turns out).
