### ISSUE TITLE
Better handle outdated WebView versions

### ISSUE THREAD

**Issue by pwithnall** [endlessm/kolibri-installer-android#159]
As per https://github.com/endlessm/kolibri-installer-android/pull/157#issuecomment-1621829305, the Android Kolibri app has some problems when run against an old (<80) WebView component.

We should:

- [x] #160
- [ ] Pass all JS through babel

**Comment by pwithnall** [comment]
@dylanmccall, how straightforward would it be to get all the JS passing through babel, as per https://github.com/endlessm/kolibri-explore-plugin/pull/693#issuecomment-1622343596? Do you think this is an oversight, or is it set up that way for a fundamental reason?

**Comment by wjt** [comment]
I see your "(we should) either" and raise you "both". iMO we should pick a target minimum Chromium version, arrange for all code to be Babel-ed for that version, and then require a WebView update if the WebView is older than that target.

**Comment by erikos** [comment]
To verify the fix, that old versions of Webview gets detected and a dialog is displayed we should probably pick a more recent [version than 80](https://github.com/endlessm/kolibri-installer-android/commit/f76db86e22db82a2627b9e9d97e18cd5de493f01#diff-9edbd184a7eb9c65bdc8450a086e924db8f3ef7a7fce767022a9f32c53bfbc1aR82). Do we have an exact version requirement? Do we have some more data when this exactly broke?

![Screenshot 2023-08-08 3 53 24 PM](https://github.com/endlessm/kolibri-installer-android/assets/3714785/98a75112-6d27-4d56-ab3c-6b82c1a15a5e)

**Comment by pwithnall** [comment]
> To verify the fix, that old versions of Webview gets detected and a dialog is displayed we should probably pick a more recent [version than 80](https://github.com/endlessm/kolibri-installer-android/commit/f76db86e22db82a2627b9e9d97e18cd5de493f01#diff-9edbd184a7eb9c65bdc8450a086e924db8f3ef7a7fce767022a9f32c53bfbc1aR82). Do we have an exact version requirement? Do we have some more data when this exactly broke?

I’ve [verified the fix](https://github.com/endlessm/kolibri-installer-android/issues/160#issuecomment-1670807988).

**Comment by pwithnall** [comment]
I’m still digging through whether babel is being run on kolibri-explore-plugin, whether it has the right config, and how exactly core-js polyfills work. More updates to come.

**Comment by pwithnall** [comment]
PR ready: https://github.com/endlessm/kolibri-explore-plugin/pull/744

**Comment by erikos** [comment]
Available in https://github.com/endlessm/kolibri-explore-plugin/releases/tag/v6.35.0 and in internal testing in the Android app.
