### ISSUE TITLE
Pre-launch report error to fix for the Android app

### ISSUE THREAD

**Issue by erikos** [endlessm/kolibri-installer-android#161]
Errors found. Fix before releasing to production.

https://play.google.com/console/u/0/developers/6541700215397866681/app/4972213255602582038/pre-launch-report/details?tab=stability&artifactId=4859829701601941167

![Image](https://user-images.githubusercontent.com/3714785/253598513-03135134-b26d-4305-b9bf-22fe68a28157.png)

**Comment by wjt** [comment]
I googled this error. It is a spurious error on Google's side and has no impact on our ability to publish new releases.

https://stackoverflow.com/questions/76391747/getting-no-active-admin-securityexception-in-android-10-how-to-resolve

https://issuetracker.google.com/issues/160907013#comment318

**Comment by wjt** [comment]
If you check out the end of the second link you will see many posts mentioning samsung SM-G981U1 as the problematic device. This is the same device our failure is from. The full backtrace shows none of our code.

![Screenshot from 2023-07-17 12-00-49](https://github.com/endlessm/kolibri-installer-android/assets/86760/5b326c12-7c3c-4dba-b25e-fa6677935d38)
