### ISSUE TITLE
Java Runtime version 55.0 is not compatible with Android SDK (class file version 61.0)

### ISSUE THREAD

**Issue by starnight** [endlessm/kolibri-installer-android#169]
The environment building of `make build_toolbox` hits Java Runtime and Android SDK compatibility issue as the error:
```
yes y | /opt/android/sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools"
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by starnight** [comment]
This error makes CI build failed https://ci.endlessos.org/job/kolibri-installer-android-pr/484/console

**Comment by starnight** [comment]
According to [SDK Build Tools release notes](https://developer.android.com/tools/releases/build-tools), I guess because of supporting Android 14 preview APIs (since Revision 34.0.0)?  If so, then according to [Which Java APIs can I use in my Java or Kotlin source code?](https://developer.android.com/build/jdks#compileSdk), Android 14 (API 34) should go with Java 17.

And, we are not alone [Class file has wrong version 61.0, should be 55.0](https://github.com/akshaaatt/Google-IAP/issues/118)

**Comment by dbnicholson** [comment]
`sdkmanager` is actually in the [cmdline-tools](https://developer.android.com/tools/releases/cmdline-tools), and sadly they seem to not be doing release notes anymore. Locally I upgraded from 9.0 to 11.0 and was able to reproduce this bug. The git history is [here](https://android.googlesource.com/platform/prebuilts/cmdline-tools/+log/refs/heads/main), although it's mostly not useful.

**Comment by starnight** [comment]
Thanks!  Verified with https://github.com/endlessm/kolibri-installer-android/pull/170#issuecomment-1667239382
