### ISSUE TITLE
Stop using the welcome-screen USB APIs on Android

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-installer-android#171]
We have [Change the initial screen so it doesn't offer the USB option.](https://github.com/endlessm/kolibri-explore-plugin/issues/732)
So, we can drop USB API corresponding Android webview and dependent code.

**Comment by erikos** [comment]
Jian-Hong is working on the removal of the whitenoise. Moving back to in progress.

**Comment by starnight** [comment]
Quick tested with Endless Key app (Ladybird 6.32-382 6.32.0-0.16.0b1-2d9d060).  It works.
