### ISSUE TITLE
Convert to Chaquopy

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/kolibri-installer-android#185]
Many reliability issues such as https://github.com/endlessm/kolibri-explore-plugin/issues/740 and https://github.com/endlessm/kolibri-explore-plugin/issues/769 can't be fixed without adding significant fixes to python-for-android. The way that it tries to bolt an Android app onto a Python app makes it really hard to use any Android features that would improve reliability. The biggest one is that Kolibri should be run as a separate bound service instead of as a separate thread in the main activity. The other is that p4a's handling of the Python interpreter is really subpar and it has to resort to killing the process whenever the launched script ends. Killing your own process is not part of the standard way to handle the Android activity lifecycle.

I've been quietly working on this in https://github.com/dbnicholson/kolibri-chaquopy/ and it is better in every regard. It's still missing a couple features we currently have here, but I don't think it would be that hard to port that work here. I think it would be a big win for the Android app to do this and stop applying duct tape to python-for-android.

**Comment by erikos** [comment]
Ready for review https://github.com/endlessm/kolibri-installer-android/pull/191

**Comment by dbnicholson** [comment]
I think what's in #191 should work well and provide rough feature parity with the current p4a app. There are a few things that I think will need work, though:

* https://phabricator.endlessm.com/T34576 - Improved animation for when the server is restarted and the page needs to be reloaded. I made a quick try last week, but it wasn't that much better. I think I don't fully understand the previous process, but it should be possible to recover it.
* https://phabricator.endlessm.com/T34551 - Clearing the browser history in some scenarios. I think this was more important when the welcome screen app needed to ask whether you wanted to install on USB or not. I can't tell if this is still needed or not.
* Currently the explore plugin version is hardcoded like in the flatpak since that makes the build more reproducible. That means it will not be automatically updated and will break the triggered release from kolibri-explore-plugin. My intention was to write a script along the lines of flatpak-external-data-checker, but I can't think of a good way to manage the flow. I'm instead going to add some gradle code that figures out what version to use.
* The installed size may be bigger than the p4a version due to the way chaquopy bundles the per-ABI python native code as described in [here](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size). I haven't closely at whether this is the case or not.

**Comment by dbnicholson** [comment]
> * Currently the explore plugin version is hardcoded like in the flatpak since that makes the build more reproducible. That means it will not be automatically updated and will break the triggered release from kolibri-explore-plugin. My intention was to write a script along the lines of flatpak-external-data-checker, but I can't think of a good way to manage the flow. I'm instead going to add some gradle code that figures out what version to use.

I put together something a bit like the endless-key-app Windows build where an "update explore version" workflow is triggered from kolibri-explore-plugin release. That updates the `exploreVersion` value in `gradle.properties` with the specified value, commits and pushes it, and then triggers the Jenkins build with `UPLOAD=true`. I'll file those PRs shortly, but the android side is on top of #191.

> * The installed size may be bigger than the p4a version due to the way chaquopy bundles the per-ABI python native code as described in [here](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size). I haven't closely at whether this is the case or not.

I still haven't taken a deep dive, but I think the p4a build suffers from the exact same problem and the chaquopy APK is actually quite a bit smaller. I chalk this up to dropping the remote shell service and the huge pile of python dependencies that required.

It's a little hard to do a complete apples to apples comparison since the purpose of the AAB is that Google Play generates an ABI specific APK on the fly whereas the APKs built by gradle have to include all ABI components. However, if you compare the debug APK of the [latest p4a build](https://ci.endlessos.org/job/kolibri-installer-android/246/) and the [latest chaquopy PR build](https://ci.endlessos.org/job/kolibri-installer-android-pr/533/), the debug APK drops from 240 MB to 192 MB. So, I think this is actually an improvement, but mostly due to dropping python dependencies as noted above.

**Comment by dbnicholson** [comment]
The PR was merged and built correctly. However, when I went to upload to internal testing, it failed due to a [syntax error](https://github.com/endlessm/kolibri-installer-android/commit/cdd72a0314908984dd1408f446c696a5568de992). Pushed a fix for that but the upload [failed again](https://ci.endlessos.org/job/kolibri-installer-android-upload/119/) saying it would exceed the 150 MB max size.

**Comment by starnight** [comment]
According to [Create and set up your app](https://support.google.com/googleplay/android-developer/answer/9859152?hl=en#zippy=%2Cmaximum-size-limit), seems like we need to slim more size down.  150MB is the maximum size.

**Comment by dbnicholson** [comment]
Indeed, the APKs now exceed the 150 MB barrier while they were a bit under with python-for-android. In order to analyze things, I had to poke at the built AAB with [bundletool](https://developer.android.com/tools/bundletool). Unfortunately, it doesn't come with the SDK as a standalone program, but you can just download a [release JAR file](https://github.com/google/bundletool/releases/download/1.15.5/bundletool-all-1.15.5.jar), rename it to `bundletool`, make it executable, and put it somewhere in `PATH`. Through the magic of binfmt_misc, it will be run with `java`.

After that, you can generate the APK set locally like `bundletool build-apks --bundle app/build/outputs/bundle/release/app-release.aab --output release.apks`. The APK set is just a zip file, so if you look inside you'll see a bunch of APK files under `splits`. What's happening is that the AAB file is split into [multiple APKs](https://developer.android.com/build/configure-apk-splits) by ABI, language and screen density. At install time, Google Play will deliver the split APKs matching those characteristics for your device rather than delivering the same gigantic APK to all devices.

To see the min and max size of the APKs that will be delivered to a device, you can run `bundletool get-size total --human-readable-sizes --apks release.apks`. Indeed, if I look at the last p4a build and the current chaquopy Jenkins build, we previously were under the limit but are now over:

```
$ bundletool get-size total --human-readable-sizes --apks p4a.apks 
MIN,MAX
145.07 MB,146.08 MB
$ bundletool get-size total --human-readable-sizes --apks jenkins-release.apks 
MIN,MAX
159.07 MB,159.84 MB
```

**Comment by dbnicholson** [comment]
Now to fixing the problem. As alluded to earlier, the biggest problem is that the way chaquopy delivers Python native components [does not work with bundles](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size). This is actually a place where python-for-android beats chaquopy since it delivers the python components as a [fake ABI specific shared library](https://python-for-android.readthedocs.io/en/latest/troubleshooting/#unpacking-an-apk). The only splitting by ABI is on [shared libraries](https://developer.android.com/ndk/guides/abis#native-code-in-app-packages), so now I understand the reason behind p4a's `libpybundle.so` tarball masquerading as a shared library.

It seems entirely possible to duplicate that process in chaquopy, but that's not a fix for today. I don't think chaquopy's suggestion of using multiple app flavors is realistic since it would be a huge pain to manage. Instead, I looked into trimming. The biggest winners I found:

* Limit the number of ABIs so that there are less unused native Python components in the APK. In the extreme you could just build for `armeabi-v7a` since all Android platforms support that either natively (`arm64-v8a` in 32 bit mode) or via emulation (`x86` and `x86_64`) since otherwise they wouldn't be able to run old Android apps.

  Emulation would suck, and our primary target is Chromebooks, which are going to be almost entirely `x86_64`. So, I think you want to keep that. However, the rare `arm64-v8a` Chromebooks can run armv7 apps natively as noted above, so I think that can be dropped. `x86` should probably just be dropped regardless. There are almost certainly no actual Android devices that are 32 bit x86 as phones and tablets are almost exclusively ARM and i686 laptops stopped being built roughly before Chromebooks existed. The only reason to support `x86` is for running the Android emulator locally on x86 32 bit host. In those extremely rare scenarios, they can still use the app through armv7 emulation.

* Remove the kolibri-explore-plugin JS source `assets` directory. This isn't used at runtime since the webpacked app in `static` is used. Kolibri doesn't distribute the `assets` source for any of its JS modules. Probably kolibri-explore-plugin didn't either before we switched it to use `setuptools_scm`.

* Remove the `loadingScreen` package bundled inside the kolibri-explore-plugin python package. The app doesn't use this at all as `loading-screen.zip` is downloaded and handled as a separate asset.

I noticed a few other things that could be pruned, but they're minor compared to those above.

**Comment by dbnicholson** [comment]
Upload [failed again](https://ci.endlessos.org/job/kolibri-installer-android-upload/120/) but for a different reason. Per https://developer.android.com/google/play/requirements/64-bit, we need to support 64 bit if 32 bit is provided. Which means adding back `arm64-v8a` if `armeabi-v7a` is included. Hopefully that's still below the size limit. Gonna try locally.

**Comment by dbnicholson** [comment]
[Success](https://ci.endlessos.org/job/kolibri-installer-android-upload/121/)! Apparently the 150 MB is really MiB as `bundletool` tells me it will be 150.94 MB but doing the conversion from unitless bytes gives me 143.9 MiB. I also noticed that our current [production release](https://play.google.com/console/developers/6541700215397866681/app/4972213255602582038/vitals/app-size) is 154 MB.

So, that just clears it for now, but ultimately I think the fix is to move the gigantic apps-bundle.zip to [Play Asset Delivery](https://developer.android.com/guide/playcore/asset-delivery). It doesn't actually look that [hard to do](https://developer.android.com/guide/playcore/asset-delivery/integrate-java) with `install-time` delivery.

**Comment by dbnicholson** [comment]
@vanessa-chang can you test 420 Narwhal 7.8 from internal testing?

**Comment by dbnicholson** [comment]
I forgot to mention that I pushed in https://github.com/endlessm/kolibri-installer-android/commit/6f389ed9a55bced25f4188d6fb15793489154cfe to add back `arm64-v8a` before trying the upload again.

**Comment by vanessa-chang** [comment]
I have tested the new 7.8 version today:

- App not responding issue is not reproduced
- Blackscreen issue is not reproduced

I have seen a new issue when I switch to another app when the app is still in the loading screen.

It will show a 404 screen but It can be recovered by restarting the app.



![Image](https://github.com/endlessm/kolibri-installer-android/assets/31236978/e8288100-aec1-49cb-8d2b-f4b46b2efb96)

I will create a separate ticket for this.
