### ISSUE TITLE
Channel view is broken

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-installer-android#190]
This issue can be reproduced on Narwhal 7.5-412 / 7.6-413.

Either the downloaded content in the discovery tab or the new content in the Library has this issue.

![Screenshot 2023-10-04 9 13 27 PM](https://github.com/endlessm/kolibri-explore-plugin/assets/31236978/152f73ad-19ae-4293-8d19-5f222cf4e150)

**Comment by vanessa-chang** [comment]
As this issue can only be reproduced in the Chromebook app, I'm moving this ticket to the android repo.

**Comment by dbnicholson** [comment]
I think this is likely caused by the update to kolibri 0.16.0-beta6 in https://github.com/learningequality/kolibri/commit/afa58e8c62bbcd960e0071dc88d1a6540b0d7ad8, but I'll look closer. We don't use `add_post_render_callback` anywhere.

**Comment by vanessa-chang** [comment]
[channel_view.txt](https://github.com/endlessm/kolibri-installer-android/files/12804621/channel_view.txt)

**Comment by manuq** [comment]
@dbnicholson the `add_post_render_callback` seems to be a Django thing https://docs.djangoproject.com/en/4.2/ref/template-response/#django.template.response.SimpleTemplateResponse.add_post_render_callback . So I wonder if this was introduced in commit 72518238 (the bump to to Kolibri 0.16.0-beta6)

**Comment by dbnicholson** [comment]
> @dbnicholson the `add_post_render_callback` seems to be a Django thing https://docs.djangoproject.com/en/4.2/ref/template-response/#django.template.response.SimpleTemplateResponse.add_post_render_callback . So I wonder if this was introduced in commit [7251823](https://github.com/endlessm/kolibri-installer-android/commit/7251823846cd6dda06a7f49b370761cc19994c93) (the bump to to Kolibri 0.16.0-beta6)

Indeed. In the code this is [emulating](https://github.com/django/django/blob/c669cf279ae7b3e02a61db4fb077030a4db80e4f/django/middleware/cache.py#L100), it checks that the response has a `render` callable before using that. I want to look closer at why that happens here, but I'll probably file that upstream. In the meantime I'll try to see if there's a reasonable downstream workaround.

**Comment by dbnicholson** [comment]
So, this is a generic explore plugin bug because `AppView` is [using `metadata_cache`](https://github.com/endlessm/kolibri-explore-plugin/blob/2f6959e20140cfab7723b4a87215c9ad4a1a8d44/kolibri_explore_plugin/views.py#L64) and that's broken in beta6 as noted above. I just reproduced this directly out of the explore plugin in my browser. Fortunately, it should be easy to fix as that's abusing `metadata_cache`, anyways.

**Comment by dbnicholson** [comment]
Moved over to https://github.com/endlessm/kolibri-explore-plugin/issues/872.

**Comment by dbnicholson** [comment]
This can be tested now in 414.
