### ISSUE TITLE
Loading screen 404 error

### ISSUE THREAD

**Issue by vanessa-chang** [endlessm/kolibri-installer-android#196]
Testing the new 7.8 version today when verifying #185, I have seen a new issue when I switch to another app when the app is still in the loading screen.

It will show a 404 screen but It can be recovered by restarting the app.

Reproduce steps:
1. Install the app 
2. Open the app3. 
3. When the app starts to load (showing Welcome to Endless Key!) switch to another app
4. Switch back to the EK app
5. Check the status

![Screenshot 2023-10-20 7 04 08 PM](https://github.com/endlessm/kolibri-installer-android/assets/31236978/d675f2bd-e1ef-496f-ab30-fdcd4eaa8a9b)

**Comment by dbnicholson** [comment]
Oh, darn. I didn't think the `loadingScreen` in the python package was used and stripped it out in #195. I guess I'll have to bring that back and hope we're still under the 150MB limit.

**Comment by dbnicholson** [comment]
Wait, no. I think this is an issue where it's trying to reload the "last URL", but the last URL was the loading screen. That saving of the last URL needs to detect that and ignore it.

**Comment by erikos** [comment]
Thanks Dan, for providing the PR, so this should be fixed with https://github.com/endlessm/kolibri-installer-android/pull/197

**Comment by erikos** [comment]
Works fine in 7.10.427 - QA pass. Tested the steps in the description, tried in all stages of the app startup to break it by switching to another app - without success.
